# Generated by Django 4.2.16 on 2024-10-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='description',
        ),
    ]
